---
title: "Schedule"
description-meta: "Detailed schedule for the Data Science for Transport Planning course, including session timings and topics."
pagetitle: "Course Schedule"
---

## Day 1: Introduction to R/RStudio

| Time          | Session                                                                 |   |
|---------------|-------------------------------------------------------------------------|:---:|
| 10:00 - 11:00 | Introduction to Data Science for Transport Planning                     |   |
| 11:00 - 12:30 | Finding, importing and cleaning transport datasets<br>- Origin-destination datasets<br>- OpenStreetMap (OSM) and Ordnance Survey (OS) OpenRoads datasets<br>- Stats19 road safety data | [{{< bi file-earmark-code size=1.5em >}}](s1.qmd)  |
| 12:30 - 13:30 | Lunch                                                                  |   |
| 13:30 - 15:00 | Origin-destination data analysis                                        | [{{< bi file-earmark-code size=1.5em >}}](s2.qmd)    |
| 15:00 - 15:15 | Break and refreshments                                                 |    |
| 15:15 - 17:00 | Routing and route network analysis<br>- Setting up an interface to a routing engine and using it to calculate routes and distances using GTFS data | [{{< bi file-earmark-code size=1.5em >}}](s3.qmd)|

: {tbl-colwidths="[20,75,5]" .striped}

## Day 2

| Time          | Session                                                                 |   |
|---------------|-------------------------------------------------------------------------|:---:|
| 09:00 - 10:45 | Spatio-temporal data<br>- Demonstration of open-access OD data with hourly resolution<br>- Demonstration with stats19 data for road safety analysis | [{{< bi file-earmark-code size=1.5em >}}](s4.qmd) |
| 10:45 - 11:15 | Break and refreshments                                                 | |
| 11:15 - 12:30 | OD Transport data visualisation                                        | [{{< bi file-earmark-code size=1.5em >}}](s5.qmd) |
| 12:30 - 13:30 | Lunch                                                                  | |
| 13:30 - 15:00 | Best practices for data science in transport planning<br>- Version control with Git and GitHub<br>- Reproducible research with Quarto | [{{< bi file-earmark-code size=1.5em >}}](s6.qmd) |
| 15:00 - 16:00 | Advanced topics<br>- Visualising large datasets<br>- Route network integration (e.g., OSM networks)<br>- Deploying your work as web applications | [{{< bi file-earmark-code size=1.5em >}}](s7.qmd)  |

: {tbl-colwidths="[20,75,5]" .striped}